### ISSUE TITLE
[Feat] userName이 없는 경우 root 클러스터링 추가

### ISSUE THREAD

**Issue by yjeongc** [AegisLenz/iam-policy#52]
## 🔥 Issue
userName이 없는 경우 root 클러스터링 추가

## ✅ TODO
- [x] userName이 없는 경우 root로 클러스터링
- [x] 클러스터링 된 root를 처리할 수 있도록 clustered_compare_policy 함수 변경
- [x] EC2 로그 예시 json 파일 추가
