### ISSUE TITLE
[Feat] 정책 2048자 이내로 생성하기

### ISSUE THREAD

**Issue by yjeongc** [AegisLenz/iam-policy#64]
## 🔥 Issue
정책 2048자 이내로 생성하기

## ✅ TODO
- [x] 정책을 서비스 별로 클러스터링해서 생성
- [x] unknown을 AWS로 바꿔서 생성
- [x] 서비스로 클러스터링된 정책과 사용자 정책을 비교하는 로직 변경
- [x] 실제 log 파일인 logs.json 파일 추가
- [x] README.md 파일 수정
